
language: android
jdk:
  - oraclejdk8

sudo: true

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.2
    - build-tools-25.0.3
    - build-tools-26.0.1
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-23
    - android-24
    - android-25
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

script:
  # Do not add the `--parallel` option to avoid the `Service is dying` issue.
  # See more here https://youtrack.jetbrains.com/issue/KT-15562.
  ./gradlew clean test