language: android
android:
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

  components:
    - tools
    - platform-tools
    - tools